---
- hosts: all
  connection: local
  gather_facts: false
  become: true

# Installs apt-get packages
  tasks:
    - name: Installing packages
      apt:
        name: "{{ apt_packages }}"
        state: "present"
      with_items: '{{ apt_packages }}'


    - name: Download terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/{{terraform_version}}/terraform_{{ terraform_version }}_linux_amd64.zip
        dest: /tmp/terraform-{{terraform_version}}.zip

    - name: Unzip downloaded Terraform archive
      unarchive:
        src: /tmp/terraform-{{terraform_version}}.zip
        dest: "{{ terraform_directory }}"
        copy: no
