---
- hosts: all
  connection: local
  gather_facts: false
  become: true


  tasks:
    - name: Add atom repository
      apt_repository:
        repo: ppa:webupd8team/atom
        filename: atom

# Update & Upgrade apt
    - name: Update apt
      apt:
        state: latest

    - name: Upgrade apt
      apt:
        upgrade: yes

# Installs apt-get packages

    - name: Install atom
      apt:
        name: atom
        state: present

    - name: Installing apt packages
      apt:
        name: "{{ apt_packages }}"
        state: "present"
      with_items: '{{ apt_packages }}'


# Installs Terraform according to Version specified in group_vars/vars.yml

    - name: Download terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/{{terraform_version}}/terraform_{{ terraform_version }}_linux_amd64.zip
        dest: /tmp/terraform-{{terraform_version}}.zip

    - name: Unzip downloaded Terraform archive
      unarchive:
        src: /tmp/terraform-{{terraform_version}}.zip
        dest: "{{ terraform_directory }}"
        copy: no
