---
- hosts: all
  connection: local
  gather_facts: false
  become: true


  tasks:
    - name: Update apt
      apt:
        state: latest

    - name: Upgrade apt
      apt:
        upgrade: yes


    - name: Installing apt packages
      apt:
        name: "{{ apt_packages }}"
        state: "present"
      with_items: '{{ apt_packages }}'

    - name: Install Atom
      apt:
        deb: "{{ atom_url }}"
        state: present

  
  # Installs Terraform according to Version specified in group_vars/vars.yml

    - name: Download terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/{{terraform_version}}/terraform_{{ terraform_version }}_linux_amd64.zip
        dest: /tmp/terraform-{{terraform_version}}.zip

    - name: Unzip Terraform archive & install
      unarchive:
        src: /tmp/terraform-{{terraform_version}}.zip
        dest: "{{ terraform_directory }}"
        copy: no


    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
